export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  MEDICAL_RECORD_UPLOAD: "MEDICAL_RECORD_UPLOAD",
  MEDICAL_RECORD_VIEW: "MEDICAL_RECORD_VIEW",

  ACCESS_REQUESTED: "ACCESS_REQUESTED",
  ACCESS_GRANTED: "ACCESS_GRANTED",
  ACCESS_REVOKED: "ACCESS_REVOKED",

  ROLE_CHANGED: "ROLE_CHANGED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
